// Generated by CoffeeScript 1.3.3
(function() {
  var HOST, MAX_HITS, Reston, c, i, n, sys, test_site, _i;

  sys = require("sys");

  Reston = require("Reston");

  c = console;

  HOST = "carlobifulco.com";

  MAX_HITS = 100;

  n = 0;

  test_site = function() {
    var o;
    n += 1;
    o = {
      parser: rest.parsers.json
    };
    rest.get("http://" + HOST + "/yaml/test?user_name=tester", o).on('complete', function(r) {
      var data, reston;
      reston = Reston.get("http://" + HOST + "/graph");
      data = {
        yaml_text: JSON.stringify(r),
        algname: "test",
        user_name: "tester"
      };
      reston.send(data);
      reston.on("data", function(r) {
        return c.log(r.toString());
      });
      return reston.on("error", function(r) {
        return c.log("BOOOD");
      });
    });
    return c.log(n);
  };

  for (i = _i = 1; 1 <= MAX_HITS ? _i <= MAX_HITS : _i >= MAX_HITS; i = 1 <= MAX_HITS ? ++_i : --_i) {
    test_site();
  }

}).call(this);
